"""Reconstruct docked ligand chemistry from a canonical SMILES template.

Docking coordinate formats such as PDBQT and PDB do not reliably preserve
bond orders, aromaticity, or formal charges.  These helpers retain the docked
heavy-atom coordinates while transferring the chemical graph from the
authoritative canonical SMILES before writing a PoseBusters-supported file.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any


TEMPLATE_MARKER = "AffiTox_template_chemistry_v1"


def _template_from_smiles(canonical_smiles: str) -> Any:
    from rdkit import Chem

    template = Chem.MolFromSmiles(canonical_smiles)
    if template is None:
        raise ValueError("RDKit could not parse canonical_smiles")
    template = Chem.RemoveHs(template)
    Chem.SanitizeMol(template)
    return template


def _connectivity_key(mol: Any) -> str:
    from rdkit import Chem

    key = Chem.MolToInchiKey(Chem.RemoveHs(mol))
    if not key:
        raise ValueError("RDKit could not generate an InChIKey")
    return key.split("-", 1)[0]


def _transfer_template_chemistry(
    docked_mol: Any,
    canonical_smiles: str,
    *,
    source_path: Path,
    source_kind: str,
) -> Any:
    from rdkit import Chem
    from rdkit.Chem import AllChem

    template = _template_from_smiles(canonical_smiles)
    if docked_mol.GetNumConformers() < 1:
        raise ValueError("Docked molecule does not contain coordinates")
    # Meeko represents multiple docking modes as conformers on one RDKit Mol.
    # PoseBusters expects one predicted conformer, so retain top-ranked mode 0.
    docked_top = Chem.Mol(docked_mol)
    top_conformer = Chem.Conformer(docked_top.GetConformer(0))
    docked_top.RemoveAllConformers()
    docked_top.AddConformer(top_conformer, assignId=True)
    docked = Chem.RemoveHs(docked_top, sanitize=False)
    if docked.GetNumAtoms() != template.GetNumAtoms():
        raise ValueError(
            "Docked/template heavy-atom count mismatch: "
            f"{docked.GetNumAtoms()} != {template.GetNumAtoms()}"
        )

    fixed = AllChem.AssignBondOrdersFromTemplate(template, docked)
    Chem.SanitizeMol(fixed)
    if _connectivity_key(fixed) != _connectivity_key(template):
        raise ValueError("Transferred graph does not match canonical_smiles")

    # Add explicit hydrogens after graph repair. Existing heavy-atom coordinates
    # remain untouched; coordinates for added hydrogens are generated by RDKit.
    fixed = Chem.AddHs(fixed, addCoords=True)
    fixed.SetProp(TEMPLATE_MARKER, "1")
    fixed.SetProp(f"source_{source_kind}", str(source_path))
    fixed.SetProp("canonical_smiles", canonical_smiles)
    return fixed


def pdbqt_to_template_mol(pdbqt_path: Path, canonical_smiles: str) -> Any:
    """Read top PDBQT pose with Meeko and transfer canonical chemistry."""
    from meeko import PDBQTMolecule, RDKitMolCreate

    pdbqt_mol = PDBQTMolecule.from_file(str(pdbqt_path))
    docked_mols = RDKitMolCreate.from_pdbqt_mol(pdbqt_mol)
    if not docked_mols or docked_mols[0] is None:
        raise ValueError(f"Meeko could not read a ligand from {pdbqt_path}")
    return _transfer_template_chemistry(
        docked_mols[0],
        canonical_smiles,
        source_path=pdbqt_path,
        source_kind="pdbqt",
    )


def pdb_to_template_mol(pdb_path: Path, canonical_smiles: str) -> Any:
    """Read docked PDB coordinates and transfer canonical chemistry."""
    from rdkit import Chem

    docked = Chem.MolFromPDBFile(
        str(pdb_path), sanitize=False, removeHs=False, proximityBonding=True
    )
    if docked is None:
        raise ValueError(f"RDKit could not read ligand coordinates from {pdb_path}")
    return _transfer_template_chemistry(
        docked,
        canonical_smiles,
        source_path=pdb_path,
        source_kind="pdb",
    )


def write_pose_molecule(mol: Any, output_path: Path) -> None:
    """Write one molecule as SDF or MOL, both supported by PoseBusters."""
    from rdkit import Chem

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.unlink(missing_ok=True)
    suffix = output_path.suffix.lower()
    if suffix == ".sdf":
        writer = Chem.SDWriter(str(output_path))
        try:
            writer.write(mol)
        finally:
            writer.close()
    elif suffix == ".mol":
        Chem.MolToMolFile(mol, str(output_path))
    else:
        raise ValueError(f"Unsupported output format {suffix!r}; use .sdf or .mol")
    if not output_path.is_file() or output_path.stat().st_size == 0:
        raise OSError(f"Failed to write molecule: {output_path}")


def load_pose_molecule(path: Path) -> Any:
    """Load one written pose without losing explicit hydrogens."""
    from rdkit import Chem

    if path.suffix.lower() == ".sdf":
        supplier = Chem.SDMolSupplier(str(path), removeHs=False)
        mol = supplier[0] if supplier and len(supplier) else None
    elif path.suffix.lower() == ".mol":
        mol = Chem.MolFromMolFile(str(path), removeHs=False)
    else:
        raise ValueError(f"Unsupported molecule format: {path.suffix}")
    if mol is None:
        raise ValueError(f"RDKit could not reload {path}")
    return mol


def connectivity_key(mol: Any) -> str:
    """Public connectivity-only InChIKey helper for validation."""
    return _connectivity_key(mol)
